In [1]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_csv("hf://datasets/adarshzolekar/foods-nutrition-dataset/foods.csv")

In [2]:
df.head()

,Food Items,Energy kcal,Carbs,Protein(g),Fat(g),Freesugar(g),Fibre(g),Cholestrol(mg),Calcium(mg)
0,Butternaan,300.0,50.0,7.0,10.0,2.0,2.0,15.0,50.0
1,Cupcake,200.0,30.0,2.0,8.0,20.0,0.5,20.0,20.0
2,Donuts,250.0,30.0,3.0,12.0,10.0,1.0,20.0,20.0
3,French Fries,312.0,41.0,3.4,15.0,0.3,3.8,0.0,20.0
4,Garlic Bread,200.0,25.0,4.0,10.0,1.0,1.0,10.0,30.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028 entries, 0 to 1027
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Food Items      1028 non-null   object
 1   Energy kcal     1028 non-null   float64
 2   Carbs           1028 non-null   float64
 3   Protein(g)      1028 non-null   float64
 4   Fat(g)          1028 non-null   float64
 5   Freesugar(g)    1028 non-null   float64
 6   Fibre(g)        1028 non-null   float64
 7   Cholestrol(mg)  1028 non-null   float64
 8   Calcium(mg)     1028 non-null   float64
dtypes: float64(8), object(1)
memory usage: 72.4+ KB

In [4]:
df.describe()

,Energy kcal,Carbs,Protein(g),Fat(g),Freesugar(g),Fibre(g),Cholestrol(mg),Calcium(mg)
count,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000
mean,234.396109,18.539475,4.784115,16.238317,8.813220,1.959883,25.686284,59.894329
std,186.581466,16.730920,3.479237,20.322553,12.319459,2.755564,44.742728,67.212037
min,6.610000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,101.840000,5.632500,2.100000,4.047500,1.160000,0.590000,0.000000,18.595000
50%,176.870000,12.250000,4.000000,9.270000,2.830000,1.325000,5.410000,40.795000
75%,312.912500,27.440000,6.645000,17.075000,11.857500,2.342500,33.422500,79.500000
max,839.330000,86.530000,21.550000,90.450000,85.570000,35.710000,345.880000,631.820000

In [5]:
df.shape

(1028, 9)

In [6]:
df.columns

Index(['Food Items', 'Energy kcal', 'Carbs', 'Protein(g)', 'Fat(g)',
       'Freesugar(g)', 'Fibre(g)', 'Cholestrol(mg)', 'Calcium(mg)'],
      dtype='object')

In [7]:
df.columns = [
    "food_item",
    "energy_kcal",
    "carbs",
    "protein_g",
    "fat_g",
    "free_sugar_g",
    "fibre_g",
    "cholesterol_mg",
    "calcium_mg"
]

In [8]:
df.columns

Index(['food_item', 'energy_kcal', 'carbs', 'protein_g', 'fat_g',
       'free_sugar_g', 'fibre_g', 'cholesterol_mg', 'calcium_mg'],
      dtype='object')

In [9]:
df.head()

,food_item,energy_kcal,carbs,protein_g,fat_g,free_sugar_g,fibre_g,cholesterol_mg,calcium_mg
0,Butternaan,300.0,50.0,7.0,10.0,2.0,2.0,15.0,50.0
1,Cupcake,200.0,30.0,2.0,8.0,20.0,0.5,20.0,20.0
2,Donuts,250.0,30.0,3.0,12.0,10.0,1.0,20.0,20.0
3,French Fries,312.0,41.0,3.4,15.0,0.3,3.8,0.0,20.0
4,Garlic Bread,200.0,25.0,4.0,10.0,1.0,1.0,10.0,30.0

In [10]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.to_csv("Food_Data_Original.csv",index=False)