In [13]:
import pandas as pd

df = pd.read_csv("../dataset/Food_Data_Original.csv")

In [14]:
df.head()

,food_item,energy_kcal,carbs,protein_g,fat_g,free_sugar_g,fibre_g,cholesterol_mg,calcium_mg
0,Butternaan,300.0,50.0,7.0,10.0,2.0,2.0,15.0,50.0
1,Cupcake,200.0,30.0,2.0,8.0,20.0,0.5,20.0,20.0
2,Donuts,250.0,30.0,3.0,12.0,10.0,1.0,20.0,20.0
3,French Fries,312.0,41.0,3.4,15.0,0.3,3.8,0.0,20.0
4,Garlic Bread,200.0,25.0,4.0,10.0,1.0,1.0,10.0,30.0

In [15]:
df["health_risk_score"] = (
    df["free_sugar_g"] * 0.4 +
    df["fat_g"] * 0.3 +
    (df["cholesterol_mg"] / 10) * 0.2 -
    df["fibre_g"] * 0.1
)

In [18]:
df.sort_values("health_risk_score", ascending=False).head()

,food_item,energy_kcal,carbs,protein_g,fat_g,free_sugar_g,fibre_g,cholesterol_mg,calcium_mg,health_risk_score
731,Butter icing,500.72,71.64,0.19,25.37,71.64,0.0,65.74,12.48,99.000000
966,Royal icing,332.58,86.53,1.74,0.02,85.57,0.0,0.00,2.87,90.238859
965,Glace icing,323.51,86.31,0.01,0.01,85.35,0.0,0.00,1.95,90.000714
732,Chocolate butter icing,469.59,61.72,3.21,24.77,59.82,0.0,54.90,31.87,85.588478
730,Chocolate glace icing,436.29,62.43,3.22,20.80,59.88,0.0,44.49,26.75,81.989601

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,99))

df["health_risk_score"] = scaler.fit_transform(
    df[["health_risk_score"]]
)